---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/menuwit1/public_html/thefranchiseprofitplaybook.com
    - /bin/cp index.html $DEPLOYPATH/index.html
    - /bin/cp headshot.jpg $DEPLOYPATH/headshot.jpg
