---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/menuwit1/public_html/thefranchiseprofitplaybook.com
    - /bin/cp index.html $DEPLOYPATH/index.html
    - /bin/cp headshot.jpg $DEPLOYPATH/headshot.jpg
    - /bin/cp favicon.svg $DEPLOYPATH/favicon.svg
    - /bin/mkdir -p $DEPLOYPATH/blog
    - /bin/cp blog/index.html $DEPLOYPATH/blog/index.html
    - /bin/cp blog/you-dont-need-better-people.html $DEPLOYPATH/blog/you-dont-need-better-people.html
